# Harjoitus 3: SQL:n perusteet

**Harjoituksen sisältö** - Harjoituksessa tehdään muutamia SQL-hakuja.

**Harjoituksen tavoite** - Harjoituksen tarkoituksena on tutustua SQL-kieleen.

### Valmistautuminen

Avaa [pgAdmin](/pgadmin) selaimeen ja kirjaudu sisään.  Avaa **Query Tool** (Valitse _trainingdatabase_ **->** Ylhäältä **Tools** **->** **Query Tool**).

### Yksinkertaisia SQL-hakuja

Seuraavaksi tutkitaan hiukan edellisessä harjoituksessa ladattuja paikkatietoaineistoja:

:::code-box
```sql
SELECT
kunta_ni1
FROM
nlsfi.hallintoalue;
```
:::

Hakuja voidaan rajoittaa **WHERE**–lausekkeella:

:::code-box
```sql
SELECT
kunta_ni1, wkb_geometry
FROM
nlsfi.hallintoalue
WHERE
maaku_ni1 = 'Lappi';
```
:::

SQL-lauseisiin voidaan myös liittää erilaisia funktioita. Funktioiden avulla voidaan esimerkiksi laskea keskiarvoja tai keskihajontoja. Seuraavassa tarkastellaan kuntien nimien pituuksia:

:::code-box
```sql
SELECT
avg(char_length(kunta_ni1)), stddev(char_length(kunta_ni1))
FROM
nlsfi.hallintoalue
WHERE
maaku_ni1 = 'Uusimaa';
```
:::

Seuraavalla SQL-lauseella saamme selville, missä maakunnissa on keskimäärin pisimmät kuntien nimet:

:::code-box
```sql
SELECT
maaku_ni1, avg(char_length(kunta_ni1))
FROM
nlsfi.hallintoalue
GROUP BY
maaku_ni1
ORDER BY
avg(char_length(kunta_ni1)) desc;
```
:::

## Harjoitukset 3 - ratkaisuavain

<button onclick="enterToken()" class="btn">Syötä ratkaisuavain</button>

## Harjoitus 3.1

Missä maakunnassa on keskimäärin pisimmät kuntien nimet?

::: code-box
```sql
SELECT ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
:::code-box
```sql
SELECT
maaku_ni1, avg(char_length(kunta_ni1))
FROM
nlsfi.hallintoalue
GROUP BY
maaku_ni1
ORDER BY
avg(char_length(kunta_ni1)) desc
LIMIT 1;
```
:::
:::

## Harjoitus 3.2

Missä maakunnassa on keskimäärin lyhimmät kuntien nimet?

:::code-box
```sql
SELECT ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

:::hidden-box
:::code-box
```sql
SELECT
maaku_ni1, avg(char_length(kunta_ni1))
FROM
nlsfi.hallintoalue
GROUP BY
maaku_ni1
ORDER BY
avg(char_length(kunta_ni1)) asc
LIMIT 1;
```
:::
:::

## Harjoitus 3.3

Mikä on Suomen pisin kunnan nimi?

:::code-box
```sql
SELECT ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

:::hidden-box
:::code-box
```sql
SELECT
kunta_ni1 as "Kunta", maaku_ni1 as "Maakunta", char_length(kunta_ni1) as "Pituus"
FROM
nlsfi.hallintoalue
ORDER BY
char_length(kunta_ni1) desc
LIMIT 1;
```
:::
:::

## Harjoitus 3.4

Montako 5 kirjaimista suomenkielistä kunnan nimeä Suomessa on?

:::code-box
```sql
SELECT ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

:::hidden-box
:::code-box
```sql
WITH ltr5 AS
(
    SELECT
    kunta_ni1 as "Kunta", maaku_ni1 as "Maakunta", char_length(kunta_ni1) as "Pituus",
    kieli_ni1, 'Ykköskieli' as "Kielisyys"
    FROM
    nlsfi.hallintoalue
    WHERE
    char_length(kunta_ni1) = 5 AND kieli_ni1 = 'Suomi'
UNION
    SELECT
    kunta_ni2 as "Kunta", maaku_ni2 as "Maakunta", char_length(kunta_ni2) as "Pituus",
    kieli_ni2, 'Kakkoskieli' as "Kielisyys"
    FROM
    nlsfi.hallintoalue
    WHERE
    char_length(kunta_ni2) = 5 AND kieli_ni2 = 'Suomi'
)

SELECT
count("Kunta") AS "5-kirjaimisia suomenkielisiä kunta"
FROM
ltr5;
```
:::
:::

## Harjoitus 3.5

Missä kunnissa suomen- ja ruotsinkielinen nimi on eri, mutta samanpituinen?

:::code-box
```sql
SELECT ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

:::hidden-box
:::code-box
```sql
SELECT
kunta_ni1, kunta_ni2, char_length(kunta_ni1) AS "Pituus"
FROM
nlsfi.hallintoalue
WHERE
kunta_ni1 <> kunta_ni2 AND char_length(kunta_ni1) = char_length(kunta_ni2)
ORDER BY
char_length(kunta_ni1) DESC;
```
:::
:::

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\




=========

## Nykyinen toteutus:

### Harjoitus 1:

Missä kunnissa suomen- ja ruotsinkielinen nimi on eri, mutta samanpituinen?

:::code-box
```sql
SELECT ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

:::hidden-box
:::code-box
```sql
SELECT
kunta_ni1, kunta_ni2, char_length(kunta_ni1) AS "Pituus"
FROM
nlsfi.hallintoalue
WHERE
kunta_ni1 <> kunta_ni2 AND char_length(kunta_ni1) = char_length(kunta_ni2)
ORDER BY
char_length(kunta_ni1) DESC;
```
:::
:::

## Vaihtoehto 1:

### Harjoitus 1:

Missä kunnissa suomen- ja ruotsinkielinen nimi on eri, mutta samanpituinen?

:::code-box
```sql
SELECT ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

:::hidden-box
:::code-box
```sql
SELECT

FROM

WHERE

ORDER BY
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

:::hidden-box
:::code-box
```sql
SELECT
kunta_ni1, kunta_ni2, char_length(kunta_ni1) AS "Pituus"
FROM
nlsfi.hallintoalue
WHERE
kunta_ni1 <> kunta_ni2 AND char_length(kunta_ni1) = char_length(kunta_ni2)
ORDER BY
char_length(kunta_ni1) DESC;
```
:::
:::

:::


## Vaihtoehto 2:

### Harjoitus 1:

Missä kunnissa suomen- ja ruotsinkielinen nimi on eri, mutta samanpituinen?

:::code-box
```sql
SELECT

FROM

WHERE

ORDER BY
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

:::hidden-box
:::code-box
```sql
SELECT
nimi_suomeksi, nimi_ruotsiksi, funktio(nimi_suomeksi) AS "Pituus"
FROM
skeema.taulu
WHERE
nimi_suomeksi <> nimi_ruotsiksi AND funktio(nimi_suomeksi) = funktio(nimi_ruotsiksi)
ORDER BY
funktio(nimi_suomeksi) DESC;
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

:::hidden-box
:::code-box
```sql
SELECT
kunta_ni1, kunta_ni2, char_length(kunta_ni1) AS "Pituus"
FROM
nlsfi.hallintoalue
WHERE
kunta_ni1 <> kunta_ni2 AND char_length(kunta_ni1) = char_length(kunta_ni2)
ORDER BY
char_length(kunta_ni1) DESC;
```
:::
:::

:::


## Vaihtoehto 3:

### Harjoitus 1:

Missä kunnissa suomen- ja ruotsinkielinen nimi on eri, mutta samanpituinen?

:::code-box
```sql
SELECT

FROM

WHERE

ORDER BY
```
:::

:::hint-box
kunta_ni1 char_length() kunta_ni2 DESC <> = nlsfi tieviiva hallintoalue
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

:::hidden-box
:::code-box
```sql
SELECT
nimi_suomeksi, nimi_ruotsiksi, funktio(nimi_suomeksi) AS "Pituus"
FROM
skeema.taulu
WHERE
nimi_suomeksi <> nimi_ruotsiksi AND funktio(nimi_suomeksi) = funktio(nimi_ruotsiksi)
ORDER BY
funktio(nimi_suomeksi) DESC;
```
:::
:::

## Vaihtoehto 4:

### Harjoitus 1:

Missä kunnissa suomen- ja ruotsinkielinen nimi on eri, mutta samanpituinen?

:::code-box
```sql
SELECT

FROM

WHERE

ORDER BY
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

:::hidden-box
:::code-box
```sql
SELECT
nimi_suomeksi, nimi_ruotsiksi, funktio(nimi_suomeksi) AS "Pituus"
FROM
skeema.taulu
WHERE
nimi_suomeksi <> nimi_ruotsiksi AND funktio(nimi_suomeksi) = funktio(nimi_ruotsiksi)
ORDER BY
funktio(nimi_suomeksi) DESC;
```
:::
:::

\

<button onclick="toggleAnswer(this)" class="btn answer_btn token">ratkaisu \<vaatii kouluttajan antaman koodin></button>

:::hidden-box
:::code-box
```sql
SELECT
kunta_ni1, kunta_ni2, char_length(kunta_ni1) AS "Pituus"
FROM
nlsfi.hallintoalue
WHERE
kunta_ni1 <> kunta_ni2 AND char_length(kunta_ni1) = char_length(kunta_ni2)
ORDER BY
char_length(kunta_ni1) DESC;
```
:::
:::

