# Foreign Data Wrapper (fdw)
Tässä osassa tutustutaan fdw:ihin csv-tiedoston lukemisen kautta.


## file_fdw -lisäosa tiedostojen lukemiseen
Asenna aluksi file_fdw-lisäosa, jonka kautta voidaan luoda fdw csv-tiedostojen lukemiseen.

::: code-box
```sql
CREATE EXTENSION file_fdw;
```
:::

Luo sitten foreign server käyttäen file_fdw fdw:tä.

::: code-box
```sql
CREATE SERVER log_server FOREIGN DATA WRAPPER file_fdw;
```
:::

Ladataan nyt vieraana tauluna sama etunimet.csv-tiedosto, kuin aikaisemmin tehdyssä harjoituksessa:

::: code-box
```sql
CREATE FOREIGN TABLE etunimet2 (
    nimi text NOT NULL,
    lukumaara integer NOT NULL,
    sukupuoli text NOT NULL
) SERVER log_server OPTIONS(filename '/home/student/data/etunimet.csv', 
                            format 'csv', header 'true');
```
:::

Tarkistetaan, että taulusta lukeminen toimii:

::: code-box
```sql
SELECT * FROM etunimet2 LIMIT 20;
```
:::

Vieraan taulun voi poistaa syntaksilla:

::: code-box
```sql
DROP FOREIGN TABLE <taulun_nimi>;
```
:::

Esimerkiksi:

::: code-box
```sql
DROP FOREIGN TABLE etunimet2;
```
:::

## Harjoitus 7.1: csv-tiedostosta lukeminen
Luo vieras taulu audit_log käyttäen tiedostoa audit_log.csv. Kenttien nimet ovat ensimmäisellä rivillä.

::: code-box
```sql
FOREIGN TABLE audit_log (
    log_time timestamp with time zone,
    user_name text,
    database_name text,
    process_id integer,
    connection_from text,
    session_id text,
    session_line_num integer,
    process_status text,
    session_start_time timestamp with time zone,
    virtual_transaction_id text,
    transaction_id integer,
    error_severity text,
    sql_state_code integer,
    message text,
    detail text,
    hint text,
    internal_query text,
    internal_query_pos text,
    context text,
    query text,
    query_pos integer,
    location text,
    application_name text,
    command_tag text,
    audit_tag text
) SERVER ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">Näytä ratkaisu</button>

::: hidden-box
::: code-box
```sql
CREATE FOREIGN TABLE audit_log (
    log_time timestamp with time zone,
    user_name text,
    database_name text,
    process_id integer,
    connection_from text,
    session_id text,
    session_line_num integer,
    process_status text,
    session_start_time timestamp with time zone,
    virtual_transaction_id text,
    transaction_id integer,
    error_severity text,
    sql_state_code integer,
    message text,
    detail text,
    hint text,
    internal_query text,
    internal_query_pos text,
    context text,
    query text,
    query_pos integer,
    location text,
    application_name text,
    command_tag text,
    audit_tag text
) SERVER log_server OPTIONS(filename '/home/student/data/audit_log.csv', 
                            format 'csv', header 'true');
```
:::
:::

Listaa audit_log-taulun rivit

::: code-box
```sql
SELECT * FROM audit_log;
```
:::

**Tarkistus:**
Aja alla oleva lauseke tarkistaaksesi, että rivejä on oikea määrä

::: code-box
```sql
SELECT count(*) FROM audit_log;
```
:::
Onko rivejä 32?


## Harjoitus 7.2: Toisesta PostgreSQL-kannasta lukeminen
Tässä harjoituksessa luetaan tietokannan postgres taulua kunnat kannan koulutus sisältä. Ota aluksi käyttöön lisäosa postgres_fdw

::: code-box
```sql
CREATE ...
```
:::
<button onclick="toggleAnswer(this)" class="btn answer_btn">Näytä ratkaisu</button>

::: hidden-box
::: code-box
```sql
CREATE EXTENSION postgres_fdw;
```
:::
:::

Luo sitten foreign server postgres_server käyttäen postgres_fdw:tä

::: code-box
```sql
CREATE SERVER postgres_server
        FOREIGN DATA WRAPPER postgres_fdw
        OPTIONS (host 'localhost', port '5432', dbname 'postgres');
```
:::

postgres_fdw:n kanssa on tehtävä myös käyttäjämäppäys, jolla nykyisen tietokannan käyttäjälle annetaan vastine toisen tietokannan parissa.

::: code-box
```sql
CREATE USER MAPPING FOR postgres
        SERVER postgres_server
        OPTIONS (user 'postgres', password '<KYSY SALASANA>');
```
:::

Koska luemme taulua kunnat, ota käyttöön nykyiseen tietokantaan lisäosa postgis.

::: code-box
```sql
CREATE ...
```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">Näytä ratkaisu</button>

::: hidden-box
::: code-box
```sql
CREATE EXTENSION postgis;
```
:::
:::

Luodaan nyt vieras taulu kunnat. Täytä arvot parametreihin schema_name ja table_name.

::: code-box
```sql
CREATE FOREIGN TABLE kunnat (
    ogc_fid integer,
    geom geometry(MultiPolygon,3067),
    nimi character varying,
    id numeric(10,0)
)
    SERVER postgres_server
    OPTIONS (schema_name 'täydennä', table_name 'täydennä');
```
:::

::: code-box
```sql
CREATE FOREIGN TABLE kunnat (
    ogc_fid integer,
    geom geometry(MultiPolygon,3067),
    nimi character varying,
    id numeric(10,0)
)
    SERVER postgres_server
    OPTIONS (schema_name 'public', table_name 'kunnat');
```
:::

**Tarkistus:**
Listaa kunnat-taulun rivejä

::: code-box
```sql
SELECT id, nimi FROM kunnat;
```
:::
Onko rivejä 95?