---
title: "Johdanto PostgreSQL:n käyttöön"
author: "Gispo Oy"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
description: "Kurssi PostgreSQL:n yleisimpiin käyttötapauksiin."
documentclass: book
link-citations: yes
---

# Johdanto


Tervetuloa kurssin harjoitusten pariin!

Näiden harjoitusten avulla voit tutustua itsenäisesti PostgreSQL-tietokantajärjestelmään. Valitse vasemmalta haluamasi aihe.

## Harjoitusmateriaalin lisenssi

* Harjoitusmateriaalit on julkaistu avoimella lisenssillä. Käytettävä lisenssi on [Creative Commons Nimeä 4.0](https://creativecommons.org/licenses/by/4.0/deed.fi).
* etunimet.csv - muodostettu 24.08.2020 aineistosta Etunimitilasto 2020-08-19, joka on jaettu lisenssillä: [Creative Commons Nimeä 4.0](https://creativecommons.org/licenses/by/4.0/deed.fi)
* ajoneuvorekisteri_schema.sql - muodostettu 25.08.2020 aineistosta Ajoneuvojen avoin data 5.8, joka on jaettu lisenssillä: [Creative Commons Nimeä 4.0](https://creativecommons.org/licenses/by/4.0/deed.fi)
* audit_log.csv on muodostettu enterprisedb -sivun esimerkeistä.
* digiroad_uusimaa.gpkg on muodostettu 7.10.2020 Digiroad-aineistosta, joka on jaettu lisenssillä: [Creative Commons Nimeä 4.0](https://creativecommons.org/licenses/by/4.0/deed.fi)
* kunnat.gpkg on muodostettu 7.10.2020 Kuntapohjaiset tilastointialueet -aineistosta, joka on jaettu lisenssillä: [Creative Commons Nimeä 4.0](https://creativecommons.org/licenses/by/4.0/deed.fi)
