version: "3"

volumes:
  postgres_data:

services:
  dbhost:
    image: kartoza/postgis:${PG_TAG}
    volumes:
    - postgres_data:/var/lib/postgresql
    - ./data/dbhost:/home/${LINUX_USER}/data
    - ./docker/init_db:/docker-entrypoint-initdb.d
    ports:
      - "5439:5432"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASS=${PG_PASS}
    restart: on-failure


  pgadmin:
    image: dpage/pgadmin4:${PGA_TAG}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  client:
    build:
      context: ./docker/client
      args:
        LINUX_USER: ${LINUX_USER}
        LINUX_USER_PASSWORD: ${LINUX_USER_PASSWORD}
    environment:
      - LINUX_USER=${LINUX_USER}
      - POSTGRES_PASS=${PG_PASS}
    depends_on:
      - dbhost
    volumes:
    - ./data/client:/home/${LINUX_USER}/data
    - ./initializer.sh:/initializer.sh

  wetty:
    image: wettyoss/wetty
    depends_on:
      - client
    environment:
      SSHHOST: 'client'
      SSHPORT: 22

  nginx:
    image: nginx
    depends_on:
      - wetty
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./harjoitukset/build:/www/html
    - ./data/client:/www/data
    - /etc/ssl/private:/etc/ssl/private:ro
    ports:
    - "80:80"
    - "443:443"

  bookdown:
    image: gispo/bookdown
    profiles: ["dev"]
    volumes:
      - "./harjoitukset:/book"
      - "./data:/data"
    environment:
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PGADMIN_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - LINUX_USER=${LINUX_USER}
      - LINUX_PASSWORD=${LINUX_USER_PASSWORD}
